server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guigb9/config-server-hyperxpress
            #username: username
          #password: password
          default-label: main
          search-paths:
            - 'hyperxpress*'
