server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          ignoreLocalSshSettings: false
          passphrase: gui1019
          uri: git@github.com:guigb9/configs-hyperxpress.git
          default-label: main
          search-paths:
            - 'hyperxpress*'
